FROM debian

ENV TZ=Asia/Tokyo
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    tcpdump \
    iproute2 \
    wireshark \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
